### PR TITLE
0.0.249: New type: gravure

### PR DESCRIPTION
**Pull request by zvezdochiot**
New type of filter (new parameters for the general filter): gravure. Solves the problem of engraving and similar images on the page.

### CODE REVIEW

**Review by mauvilsa — CHANGES_REQUESTED** [review]
I have several comments that I think should be addressed before considering merging this pull request.

1) Adding a new technique with just a name and no explanation of it is not very useful for other people that might use this tool. The readme should be modified referencing all the techniques that are supported. Right now only Sauvola is mentioned, so the other two techniques should be mentioned: wolf and gravure. For wolf just add the reference below. I have been unable to find anywhere where gravure is explained. Is this just something you are working now? If this technique hasn't been published yet, then at least create a blog post describing it, or a short paper uploaded to arXiv and reference that.

    Wolf, Christian, J-M. Jolion, and Francoise Chassaing. "Text localization, enhancement
    and binarization in multimedia documents." Object recognition supported by user interaction
    for service robots. Vol. 2. IEEE, 2002.

2) There are big changes in the code and since before there weren't any unit tests it is not possible to check that the previous techniques work identically as before. Would you mind adding toy example images with unit tests that apply the techniques and checking that the result is the one expected? I guess this would have a new pull request before these is merged. Then we could merge the unit test here and be sure that nothing has changed.

3) If there are unit tests implemented then I wouldn't mind the big changes you made. Though I do have a question. In some functions you have changed variable names: cropW -> xmax, cropH -> xmax. However, there is quite a difference between width and height of a crop window and the maximum x and y values of this crop window. You have changed everything so that the functions now receive the maximum values? I don't see this in the changes. If what the functions receive are effectively the width and height of the crop window, I would suggest to change back to cropW and cropH. Using xmax and ymax is very misleading making the code harder to understand.

**Comment by zvezdochiot** [comment]
>Adding a new technique with just a name and no explanation of it is

No new technology, the same `wolf` (aka` Chistian`) with only other experimentally selected parameters [wolf={M=min(m),S=max(s)},gravure={M=(mI+min(m))/2,S=(sI+max(s))/2}].
```
wolf:
M |   ^####  |
S | ####^    |
gravure:
M |   #^###  |
S | ###^#    |
```

>There are big changes in the code and since before there weren't any unit tests it is not possible to check that the previous techniques work identically as before.

Checked specifically on a set of images without creating tests.

>In some functions you have changed variable names: cropW -> xmax, cropH -> xmax.

Not. I removed the unnecessary action in your code (overheads):
* Before calling the function, you calculate (W and H) = (max-min)
* At the beginning of each function, you calculate max = min + (W, H)
See https://github.com/mauvilsa/imgtxtenh/pull/10/commits/669674f83f3b50baa604b75e86e09821c9d8d7ff . The code is equivalent, but without unnecessary gestures.

**Comment by zvezdochiot** [comment]
Origin:  
 Orig  
Sauvola:  
 Sauvola  
Wolf:  
 Wolf  
Gravure:  
 Gravure

**Comment by zvezdochiot** [comment]
⚠️ Not resolved !!!

**Pull request closed without merging**
